name: Generate Buddy Mono Font to Current Repo...

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          show-progress: true
          fetch-depth: 1

      - name: Checkout Iosevka
        uses: actions/checkout@v6
        with:
          repository: be5invis/Iosevka
          show-progress: true
          path: iosevka-src
          fetch-depth: 1

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ttfautohint python3

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/Krypton'
          check-latest: true

      - name: Copy Custom Build Plan
        run: cp .github/buddy-mono/private-build-plans.toml iosevka-src/

      - name: Install Dependencies And Build All Font Formats
        run: |
          cd iosevka-src
          npm install
          npm run build -- ttf::BuddyMono

      - name: Verify Build Output
        run: |
          if [ ! -d "iosevka-src/dist/BuddyMono/TTF" ] || [ ! -d "iosevka-src/dist/BuddyMono/WOFF2" ]; then
            exit 1
          fi
          echo "TTF And WOFF2 Build Directories Verified."

      - name: Copy Fonts I Need
        run: |
          mkdir -p ./BuddyMono
          cd iosevka-src/dist/BuddyMono
          cp iosevka-src/dist/BuddyMono/*.ttf ./BuddyMono/
          ls -lah ./BuddyMono

      - name: Deploy to GitHub Repository
        run: |
          git config --global user.email ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git config diff.nocase.textconv "tr '[:upper:]' '[:lower:]'"
          git status
          git add --all

          if git diff --cached --quiet; then
            echo "No Changes To Commit."
            exit 0
          fi

          git commit -m 'Update::Buddy Mono'
          git pull --rebase --autostash
          git push
